# If the failing case is modified to have the "issue" module apply the test-plugin, the issue is solved
name: Run reproducer-3 on each commit
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11

    - name: Switch modules # remove a-test, add z-test
      run: |
        sed -i 's/include(":a-test")/\/\/include(":a-test")/' settings.gradle.kts
        sed -i 's/\/\/include(":z-test")/include(":z-test")/' settings.gradle.kts

    - name: Add test-plugin to issue module
      run: |
        sed -i '4i plugins { id("com.example.test-plugin") }' issue/build.gradle.kts

    - name: Working Case (despite alphabetical order)
      run: |
        ./gradlew issue:help --configuration-cache
        ./gradlew issue:help --configuration-cache
        touch issue/test.txt
        echo "created test.txt"
        ./gradlew issue:help --configuration-cache
        rm issue/test.txt
        echo "removed test.txt"
        ./gradlew issue:help --configuration-cache
