name: Run reproducer on each commit
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11
    - run: |
        ./gradlew issue:help --configuration-cache
        ./gradlew issue:help --configuration-cache
        touch issue/test.txt
        ./gradlew issue:help --configuration-cache
        rm issue/test.txt
        ./gradlew issue:help --configuration-cache
        sed -i 's/include(":a-test")/\/\/include(":a-test")/' settings.gradle.kts
        sed -i 's/\/\/include(":z-test")/include(":z-test")/' settings.gradle.kts
        ./gradlew issue:help --configuration-cache
        ./gradlew issue:help --configuration-cache
        touch issue/test.txt
        ./gradlew issue:help --configuration-cache
        rm issue/test.txt
        ./gradlew issue:help --configuration-cache
